@startuml tester

' Interfaces/classes
interface OutputDeviceInterface {
    + init()
    + write_sample()
    + deinit()
}

class NiUsb6211 {
    + init()
    + write_sample()
    + deinit()
}

interface InputDeviceInterface {
    + init()
    + read_sample()
    + deinit()
}

class SerialDevice {
    + init()
    + read_sample()
    + deinit()
}

class Tester {
    + inputDevice
    + outputDevice
    + init()
    + run_tests()
    + output_data()
    + deinit()
}

'  Relations
OutputDeviceInterface <|-left- NiUsb6211
InputDeviceInterface <|-right- SerialDevice

Tester <-left- OutputDeviceInterface
Tester <-right- InputDeviceInterface

@enduml
